[workspace]
resolver = "2"
members = [
  "backend",
  "crates/simadmin-agent",
  "crates/simadmin-auth",
  "crates/simadmin-device-core",
  "crates/simadmin-device-runtime",
  "crates/simadmin-notify",
  "crates/simadmin-protocol",
  "crates/simadmin-sms-core",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
